### ISSUE TITLE
Service seems to be down

### ISSUE THREAD

**Issue by kumavis** [kobigurk/etherlisten#1]
currently in china so not sure if its the poor internet connection or what but wanted to show my ethereum students this service. doesnt seem to work here! my guess is that your websocket node is not forwarding txs, but close this issue if wrong.

**Comment by kobigurk** [comment]
Thanks, it stops from time to time. I'll be using a different method in the future to make it more reliable.

**Comment by kumavis** [comment]
thanks! though now im seeing double transactions for some reason - no biggie

we are enjoying listening to the ethereum network now : )
